"""initial migration

Revision ID: 107ce2a0455e
Revises: 
Create Date: 2023-03-22 14:18:30.463210

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "107ce2a0455e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "google_req",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_text", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_text"),
    )
    op.create_table(
        "settings_cycle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_string", sa.Integer(), nullable=True),
        sa.Column("wait_interval", sa.Integer(), nullable=True),
        sa.Column("search_page_number", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "result_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_req", sa.Integer(), nullable=True),
        sa.Column("request_text", sa.Text(), nullable=True),
        sa.Column("res_link", sa.Text(), nullable=True),
        sa.Column("res_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["id_req"], ["google_req.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("result_info")
    op.drop_table("settings_cycle")
    op.drop_table("google_req")
    # ### end Alembic commands ###
