"""Initial migration

Revision ID: 3a8a19e414d6
Revises: 
Create Date: 2023-03-15 22:23:48.117422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8a19e414d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_req',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_text', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_text')
    )
    op.create_table('settings_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_string', sa.Integer(), nullable=True),
    sa.Column('wait_interval', sa.Integer(), nullable=True),
    sa.Column('search_page_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_req', sa.Integer(), nullable=True),
    sa.Column('request_text', sa.String(length=100), nullable=True),
    sa.Column('res_link', sa.String(length=5000), nullable=True),
    sa.Column('res_text', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['id_req'], ['google_req.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_info')
    op.drop_table('settings_cycle')
    op.drop_table('google_req')
    # ### end Alembic commands ###
