"""Initial migration.

Revision ID: 882465a4da72
Revises: 
Create Date: 2023-03-09 13:13:44.547828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882465a4da72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_req',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_text', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_text')
    )
    op.create_table('result_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_string', sa.Integer(), nullable=True),
    sa.Column('wait_interval', sa.Integer(), nullable=True),
    sa.Column('search_page_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_cycle')
    op.drop_table('result_info')
    op.drop_table('google_req')
    # ### end Alembic commands ###
