"""Initial migration.

Revision ID: 8f9896e9db51
Revises: f045afb5a39a
Create Date: 2023-03-11 18:14:39.497309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9896e9db51'
down_revision = 'f045afb5a39a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_info', schema=None) as batch_op:
        batch_op.alter_column('res_link',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=5000),
               existing_nullable=True)
        batch_op.alter_column('res_text',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_info', schema=None) as batch_op:
        batch_op.alter_column('res_text',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('res_link',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
